import {
  // Housing
  House,
  KeyRound,
  Hammer,
  Wrench,
  Building,
  Building2,
  Warehouse,
  DoorOpen,
  Bed,
  Sofa,
  // Utilities
  Zap,
  Flame,
  Droplet,
  Wifi,
  Phone,
  Plug,
  Lightbulb,
  Router,
  SatelliteDish,
  Thermometer,
  // Food
  Utensils,
  UtensilsCrossed,
  Coffee,
  Pizza,
  Apple,
  ShoppingBasket,
  Soup,
  Cake,
  IceCreamCone,
  Wine,
  Beer,
  Sandwich,
  // Transportation
  Car,
  CarFront,
  Bus,
  TrainFront,
  Fuel,
  Bike,
  Plane,
  Ship,
  CircleParking,
  Truck,
  Navigation,
  // Health and personal care
  HeartPulse,
  Stethoscope,
  Pill,
  Syringe,
  Eye,
  Dumbbell,
  Cross,
  ShieldPlus,
  Scissors,
  Sparkles,
  Activity,
  // Shopping
  ShoppingCart,
  ShoppingBag,
  Shirt,
  Gem,
  Watch,
  Tag,
  Package,
  Store,
  // Entertainment
  Tv,
  Gamepad2,
  Film,
  Music,
  Clapperboard,
  Ticket,
  PartyPopper,
  Camera,
  Headphones,
  BookOpen,
  // Travel
  PlaneTakeoff,
  Luggage,
  Map,
  MapPin,
  Compass,
  Tent,
  TreePalm,
  Globe,
  // Education
  GraduationCap,
  Book,
  BookOpenText,
  Pencil,
  Backpack,
  Notebook,
  Ruler,
  Calculator,
  // Gifts and donations
  Gift,
  HeartHandshake,
  HandCoins,
  PackagePlus,
  // Savings and investments
  PiggyBank,
  Landmark,
  TrendingUp,
  Wallet,
  Coins,
  Banknote,
  ChartLine,
  Percent,
  CircleDollarSign,
  // General / other
  LayoutGrid,
  Briefcase,
  Users,
  Baby,
  PawPrint,
  CreditCard,
  WalletCards,
  Receipt,
  Calendar,
  Bell,
  Smartphone,
  Printer,
} from "lucide-react";

export const CATEGORY_ICONS = {
  // Housing
  house: House,
  "key-round": KeyRound,
  hammer: Hammer,
  wrench: Wrench,
  building: Building,
  "building-2": Building2,
  warehouse: Warehouse,
  "door-open": DoorOpen,
  bed: Bed,
  sofa: Sofa,
  // Utilities
  zap: Zap,
  flame: Flame,
  droplet: Droplet,
  wifi: Wifi,
  phone: Phone,
  plug: Plug,
  lightbulb: Lightbulb,
  router: Router,
  "satellite-dish": SatelliteDish,
  thermometer: Thermometer,
  // Food
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  coffee: Coffee,
  pizza: Pizza,
  apple: Apple,
  "shopping-basket": ShoppingBasket,
  soup: Soup,
  cake: Cake,
  "ice-cream-cone": IceCreamCone,
  wine: Wine,
  beer: Beer,
  sandwich: Sandwich,
  // Transportation
  car: Car,
  "car-front": CarFront,
  bus: Bus,
  "train-front": TrainFront,
  fuel: Fuel,
  bike: Bike,
  plane: Plane,
  ship: Ship,
  "circle-parking": CircleParking,
  truck: Truck,
  navigation: Navigation,
  // Health and personal care
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  eye: Eye,
  dumbbell: Dumbbell,
  cross: Cross,
  "shield-plus": ShieldPlus,
  scissors: Scissors,
  sparkles: Sparkles,
  activity: Activity,
  // Shopping
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  gem: Gem,
  watch: Watch,
  tag: Tag,
  package: Package,
  store: Store,
  // Entertainment
  tv: Tv,
  "gamepad-2": Gamepad2,
  film: Film,
  music: Music,
  clapperboard: Clapperboard,
  ticket: Ticket,
  "party-popper": PartyPopper,
  camera: Camera,
  headphones: Headphones,
  "book-open": BookOpen,
  // Travel
  "plane-takeoff": PlaneTakeoff,
  luggage: Luggage,
  map: Map,
  "map-pin": MapPin,
  compass: Compass,
  tent: Tent,
  "tree-palm": TreePalm,
  globe: Globe,
  // Education
  "graduation-cap": GraduationCap,
  book: Book,
  "book-open-text": BookOpenText,
  pencil: Pencil,
  backpack: Backpack,
  notebook: Notebook,
  ruler: Ruler,
  calculator: Calculator,
  // Gifts and donations
  gift: Gift,
  "heart-handshake": HeartHandshake,
  "hand-coins": HandCoins,
  "package-plus": PackagePlus,
  // Savings and investments
  "piggy-bank": PiggyBank,
  landmark: Landmark,
  "trending-up": TrendingUp,
  wallet: Wallet,
  coins: Coins,
  banknote: Banknote,
  "chart-line": ChartLine,
  percent: Percent,
  "circle-dollar-sign": CircleDollarSign,
  // General / other
  "layout-grid": LayoutGrid,
  briefcase: Briefcase,
  users: Users,
  baby: Baby,
  "paw-print": PawPrint,
  "credit-card": CreditCard,
  "wallet-cards": WalletCards,
  receipt: Receipt,
  calendar: Calendar,
  bell: Bell,
  smartphone: Smartphone,
  printer: Printer,
} as const;

export const DEFAULT_CATEGORY_ICON = "layout-grid" satisfies keyof typeof CATEGORY_ICONS;

export function isCategoryIcon(value: string): value is keyof typeof CATEGORY_ICONS {
  return Object.hasOwn(CATEGORY_ICONS, value);
}
