import { describe, expect, it } from "vitest";

import { buildListQueries } from "@/lib/transactions/list-query";
import {
  parseTransactionFilters,
  type TransactionFilters,
} from "@/lib/validations/transaction-filters";

const TODAY = new Date("2026-08-16T12:00:00.000Z");

const filtersFrom = (params: Record<string, string> = {}): TransactionFilters =>
  parseTransactionFilters(params, TODAY);

const build = (params: Record<string, string> = {}, categorySortNames = new Map<string, string>()) =>
  buildListQueries({ userId: "user-1", filters: filtersFrom(params), categorySortNames });

describe("buildListQueries", () => {
  describe("arm selection", () => {
    it("includes all three arms by default", () => {
      const { rows } = build();
      expect(rows.text).toContain("'single' AS \"kind\"");
      expect(rows.text).toContain("'installment' AS \"kind\"");
      expect(rows.text).toContain("'recurring' AS \"kind\"");
    });

    it("includes only the one-off arm for show=single", () => {
      const { rows } = build({ show: "single" });
      expect(rows.text).toContain("'single' AS \"kind\"");
      expect(rows.text).not.toContain("'installment' AS \"kind\"");
      expect(rows.text).not.toContain("'recurring' AS \"kind\"");
    });

    it("includes only the installment arm for show=installments", () => {
      const { rows } = build({ show: "installments" });
      expect(rows.text).toContain("'installment' AS \"kind\"");
      expect(rows.text).not.toContain("'single' AS \"kind\"");
    });

    it("includes only the ongoing arm for show=recurring", () => {
      const { rows } = build({ show: "recurring" });
      expect(rows.text).toContain("'recurring' AS \"kind\"");
      expect(rows.text).not.toContain("'single' AS \"kind\"");
    });
  });

  describe("row visibility", () => {
    // The original requirement: a row generated by an ongoing recurrence is
    // never listed. It is represented by its definition instead.
    it("excludes generated rows from the one-off arm", () => {
      expect(build({ show: "single" }).rows.text).toContain(
        "t.recurring_transaction_id IS NULL",
      );
    });

    it("restricts the installment arm to fixed-count parents", () => {
      expect(build({ show: "installments" }).rows.text).toContain(
        "r.fixed_occurrences_count = true",
      );
    });

    it("restricts the ongoing arm to non-fixed definitions", () => {
      expect(build({ show: "recurring" }).rows.text).toContain(
        "r.fixed_occurrences_count = false",
      );
    });

    it("excludes soft-deleted rows from every arm", () => {
      const { rows } = build();
      expect(rows.text.match(/deactivated_at IS NULL/g)?.length).toBeGreaterThanOrEqual(4);
    });
  });

  describe("series numbering", () => {
    // Numbered before the period filter and before the soft-delete filter, so
    // deleting occurrence 3 does not renumber 4-12, and a window starting
    // mid-series still reads 7/12.
    //
    // Checked against the installment arm's own SELECT rather than against
    // "UNION ALL": show=installments selects a single arm, so no UNION ALL
    // text exists in this query at all, and comparing against indexOf's -1
    // sentinel would make the assertion unsatisfiable regardless of the CTE's
    // real position.
    it("numbers occurrences in a CTE over every generated row", () => {
      const { rows } = build({ show: "installments" });
      expect(rows.text).toContain("PARTITION BY t.recurring_transaction_id");
      expect(rows.text.indexOf("WITH series")).toBeLessThan(
        rows.text.indexOf('\'installment\' AS "kind"'),
      );
    });

    // The property the comment above actually depends on: the CTE's own
    // WHERE clause carries no `deactivated_at` and no date-range predicate,
    // so a row keeps the index it was numbered with even after a sibling is
    // later deleted or a window is applied that excludes it. Isolating the
    // CTE's own text (rather than checking rows.text as a whole, which
    // legitimately contains both elsewhere, from the arm predicates) is
    // what actually pins this — a whole-text check would pass even if the
    // CTE itself grew those filters.
    it("numbers over every recurring-linked row, unfiltered by soft-delete or the period", () => {
      const { rows } = build({ show: "installments" });
      const cteText = rows.text.slice(
        rows.text.indexOf("WITH series"),
        rows.text.indexOf("SELECT entries.*"),
      );
      expect(cteText).toContain("t.user_id = ");
      expect(cteText).toContain("t.recurring_transaction_id IS NOT NULL");
      expect(cteText).not.toContain("deactivated_at");
      // `t.date` itself legitimately appears as the window's own tie-break
      // (`ORDER BY t.date, t.id`) — that orders ties within a partition, it
      // doesn't exclude rows. A range predicate is what would exclude rows,
      // and that's what must be absent.
      expect(cteText).not.toContain(">=");
    });
  });

  describe("ordering", () => {
    it("defaults to date descending", () => {
      expect(build().rows.text).toContain('entries."effectiveDate" DESC');
    });

    it("ends every ordering with the same total tie-break", () => {
      for (const sort of ["date", "amount", "category", "description"]) {
        expect(build({ sort }).rows.text).toContain(
          'entries."effectiveDate" DESC, entries."kind" ASC, entries."id" ASC',
        );
      }
    });

    it("sorts amounts numerically, not as text", () => {
      expect(build({ sort: "amount" }).rows.text).toContain('(entries."amount")::numeric');
    });

    it("puts empty descriptions last in both directions", () => {
      expect(build({ sort: "description", dir: "asc" }).rows.text).toContain("NULLS LAST");
      expect(build({ sort: "description", dir: "desc" }).rows.text).toContain("NULLS LAST");
    });

    it("honours the direction", () => {
      expect(build({ dir: "asc" }).rows.text).toContain('entries."effectiveDate" ASC');
    });
  });

  describe("category ordering", () => {
    // A preset category stores English in `name`; ordering on the column
    // would sort a pt-BR list by words the user never sees.
    it("joins the resolved names only when sorting by category", () => {
      const names = new Map([["cat-1", "Alimentação"]]);
      expect(build({ sort: "category" }, names).rows.text).toContain("AS cat(id, sort_name)");
      expect(build({ sort: "date" }, names).rows.text).not.toContain("AS cat(id, sort_name)");
    });

    it("passes each resolved name as a parameter, never inlined", () => {
      const names = new Map([["cat-1", "Alimentação"]]);
      expect(build({ sort: "category" }, names).rows.values).toContain("Alimentação");
      expect(build({ sort: "category" }, names).rows.text).not.toContain("Alimentação");
    });

    it("still orders when the user has no categories", () => {
      const { rows } = build({ sort: "category" }, new Map());
      expect(rows.text).toContain("ORDER BY");
      // "ORDER BY" alone is unconditionally true here — sort=category always
      // emits one. What actually needs pinning is that the empty-map branch
      // fired: a match-nothing fallback join, so `cat.sort_name` stays a
      // valid reference instead of an error.
      expect(rows.text).toContain("AS cat ON false");
    });
  });

  describe("filters", () => {
    it("scopes every query to the session user", () => {
      expect(build().rows.values).toContain("user-1");
    });

    it("adds no optional predicate when nothing is filtered", () => {
      const { rows } = build();
      expect(rows.text).not.toContain("category_id = ");
      expect(rows.text).not.toContain("card_id = ");
    });

    it("filters by category, card, and type when asked", () => {
      const { rows } = build({ category: "cat-1", card: "card-1", type: "INCOME" });
      expect(rows.values).toContain("cat-1");
      expect(rows.values).toContain("card-1");
      expect(rows.values).toContain("INCOME");
    });

    // `to` is inclusive for the user, so the exclusive bound is the next day.
    it("turns the inclusive end date into an exclusive next-day bound", () => {
      const { rows } = build({ from: "2026-03-01", to: "2026-03-31" });
      const dates = rows.values.filter((value): value is Date => value instanceof Date);
      expect(dates.map((date) => date.toISOString())).toContain("2026-03-01T00:00:00.000Z");
      expect(dates.map((date) => date.toISOString())).toContain("2026-04-01T00:00:00.000Z");
    });
  });

  describe("pagination", () => {
    it("offsets by page size", () => {
      expect(build({ page: "3" }).rows.values).toContain(100);
      expect(build({ page: "1" }).rows.values).toContain(0);
    });

    it("counts without ordering or limiting", () => {
      const { total } = build({ page: "3" });
      expect(total.text).toContain("COUNT(*)");
      expect(total.text).not.toContain("LIMIT");
      expect(total.text).not.toContain("ORDER BY");
    });

    it("counts the same rows the page query returns", () => {
      const { total } = build({ show: "single" });
      expect(total.text).toContain("t.recurring_transaction_id IS NULL");
      expect(total.text).not.toContain("'recurring' AS \"kind\"");
    });
  });

  // The installment arm is the only place `rows` and `total` diverge in SQL
  // shape: `total` skips `JOIN series s ON s.id = t.id` because counting
  // doesn't read `seriesIndex`, and that join never filters a row (see
  // `installmentArm`'s doc comment). Every other arm is byte-identical
  // between the two paths, which is why "counts the same rows the page
  // query returns" above — exercised only against show=single — would pass
  // unchanged whether or not that divergence existed. These tests pin the
  // one path where it actually matters: that `withSeries` drops *only* the
  // non-filtering lookup, and nothing that decides which rows count.
  describe("count/page parity for the installment arm", () => {
    it("keeps every installment-arm filtering predicate in both the page and count query", () => {
      for (const show of ["installments", "all"] as const) {
        const { rows, total } = build({ show });
        for (const predicate of [
          "r.fixed_occurrences_count = true",
          "r.deactivated_at IS NULL",
          "t.deactivated_at IS NULL",
          "t.user_id = ",
          "t.date >= ",
          "t.date < ",
        ]) {
          expect(rows.text).toContain(predicate);
          expect(total.text).toContain(predicate);
        }
      }
    });

    it("drops the series lookup only from the count query, never from the page query", () => {
      for (const show of ["installments", "all"] as const) {
        const { rows, total } = build({ show });
        expect(rows.text).toContain("JOIN series");
        expect(total.text).not.toContain("JOIN series");
      }
    });

    it("carries the same filter parameters in both queries, aside from the CTE's own lookup and pagination", () => {
      for (const show of ["installments", "all"] as const) {
        const { rows, total } = build({ show, category: "cat-1", card: "card-1", type: "INCOME" });
        // `rows` always leads with the `series` CTE's own `userId`
        // parameter (present regardless of which arms are selected) and
        // always trails with LIMIT/OFFSET; strip both ends to compare the
        // filter parameters the two queries otherwise share exactly.
        const rowsFilterValues = rows.values.slice(1, rows.values.length - 2);
        expect(rowsFilterValues).toEqual(total.values);
      }
    });
  });
});
